version: '3.7'

services:
    db:
        image: postgres:14.1
        volumes:
            - pg_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: shop
    django:
        container_name: django_app
        build:
            context: ./
            dockerfile: Dockerfile
        command: bash -c "python /usr/src/api manage.py migrate --noinput &&
                 python /usr/src/api/manage.py runserver 0.0.0.0:8000"
        volumes: 
            - .:/usr/src/api
        ports:
            - 8000:8000
        depends_on:
            - db
volumes:
    pg_data:
